services:
  server-app:
    build: 
      context: .
      dockerfile: ./backend/deploy/Dockerfile
    container_name: server_app
    restart: always
    depends_on:
      - pgsql
    ports:
      - "8000:8000"
    networks:
      - backend

  pgsql:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: testovoye
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - pgsql
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  pgsql_data:
  pgadmin_data:

networks:
  backend: