definitions:
  domain.PaginatedPersons:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Person'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
      totalPages:
        type: integer
    type: object
  domain.Person:
    properties:
      age:
        type: integer
      createdAt:
        type: string
      gender:
        type: string
      id:
        type: string
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
      updatedAt:
        type: string
    type: object
  v1.ErrorResponse:
    properties:
      error:
        description: |-
          Описание ошибки
          example: invalid input body
        type: string
    type: object
  v1.createPersonResponse:
    properties:
      id:
        description: |-
          UUID нового Person
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        type: string
    type: object
  v1.newPersonInput:
    properties:
      name:
        description: |-
          Name имя человека
          Required: true
          Min Length: 2
          Max Length: 100
        maxLength: 100
        minLength: 2
        type: string
      patronymic:
        description: |-
          Patronymic отчество (необязательно)
          Min Length: 2
          Max Length: 100
        maxLength: 100
        minLength: 2
        type: string
      surname:
        description: |-
          Surname фамилия человека
          Required: true
          Min Length: 2
          Max Length: 100
        maxLength: 100
        minLength: 2
        type: string
    required:
    - name
    - surname
    type: object
  v1.simpleMessageResponse:
    properties:
      message:
        description: |-
          Сообщение
          example: success
        type: string
    type: object
  v1.updatePersonInput:
    properties:
      age:
        description: |-
          Age новый возраст (необязательно)
          Minimum: 0
          Example: 30
        minimum: 0
        type: integer
      gender:
        description: |-
          Gender новый пол (необязательно)
          Example: female
        type: string
      id:
        description: |-
          ID идентификатор Person (UUID)
          Required: true
          Example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        type: string
      name:
        description: |-
          Name новое имя (необязательно)
          Min Length: 2
          Max Length: 100
        maxLength: 100
        minLength: 2
        type: string
      nationality:
        description: |-
          Nationality новый код страны (необязательно)
          Example: US
        type: string
      patronymic:
        description: |-
          Patronymic новое отчество (необязательно)
          Min Length: 2
          Max Length: 100
        maxLength: 100
        minLength: 2
        type: string
      surname:
        description: |-
          Surname новая фамилия (необязательно)
          Min Length: 2
          Max Length: 100
        maxLength: 100
        minLength: 2
        type: string
    required:
    - id
    type: object
info:
  contact: {}
paths:
  /person:
    delete:
      consumes:
      - application/json
      parameters:
      - description: UUID идентификатор Person
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.simpleMessageResponse'
        "400":
          description: ID не указан или неверный формат
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Ошибка при удалении из БД
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Удалить Person по ID
      tags:
      - Person
    get:
      consumes:
      - application/json
      parameters:
      - description: Фильтрация по имени (partial match)
        in: query
        name: name
        type: string
      - description: Фильтрация по фамилии (partial match)
        in: query
        name: surname
        type: string
      - description: Минимальный возраст
        in: query
        minimum: 0
        name: min_age
        type: integer
      - description: Максимальный возраст
        in: query
        minimum: 0
        name: max_age
        type: integer
      - description: Пол (male/female)
        in: query
        name: gender
        type: string
      - description: Код страны (ISO Alpha-2)
        in: query
        name: nationality
        type: string
      - default: 1
        description: Страница
        in: query
        minimum: 1
        name: page
        type: integer
      - default: 10
        description: Размер страницы
        in: query
        maximum: 100
        minimum: 1
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PaginatedPersons'
        "400":
          description: Неверные query-параметры
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Ошибка при выборке из БД
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Получить список Person с фильтрацией и пагинацией
      tags:
      - Person
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные нового Person
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.newPersonInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.createPersonResponse'
        "400":
          description: Неверный формат входных данных
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Создать нового Person
      tags:
      - Person
    put:
      consumes:
      - application/json
      parameters:
      - description: Данные для обновления Person
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.updatePersonInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.simpleMessageResponse'
        "400":
          description: Неправильный формат входных данных или неверный UUID
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Ошибка при обновлении в БД
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Обновить существующего Person
      tags:
      - Person
swagger: "2.0"
